### ISSUE TITLE
Give Kapou'e traits

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/Son_Of_The_Black_Eye_Easy_Edition#7]
mentioned here: https://forums.serenesforest.net/index.php?/topic/86633-parrhesia-and-integritys-guide-to-surviving-wesnoth/&do=findComment&comment=5445198

**Comment by knyghtmare** [comment]
Intelligent: He is not obstinate like the usual Orc chieftain and displays rational thought.
Fearless/Strong: Either one would do. Personally, I'd pick Fearless since I have never taken Kapou'e for a coward.

**Comment by cooljeanius** [comment]
...actually, on second thought, while I'm at it, I should factor out the declaration of Kapou'e's side out into a macro so I don't have to manually put his traits into every single scenario...

**Comment by knyghtmare** [comment]
> ...actually, on second thought, while I'm at it, I should factor out the declaration of Kapou'e's side out into a macro so I don't have to manually put his traits into every single scenario...


Actually adding traits in only the first scenario works for any scenario as he is the leader and is present in every scenario.

**Comment by cooljeanius** [comment]
still, I want to make a macro anyways though

**Comment by cooljeanius** [comment]
oh, while I'm at it, I guess I ought to give Al'Brock and Flar'Tar traits, too...

**Comment by cooljeanius** [comment]
ok this should be fixed for Kapou'e in 72909e72c96a5832e079a47dd2829ae221535939; giving Al'Brock and Flar'Tar traits would be a separate bug, I guess...

**Comment by cooljeanius** [comment]
> ...giving Al'Brock and Flar'Tar traits would be a separate bug, I guess...

ok yeah I made that bug #8

**Comment by Ashmyr** [comment]
Eh.. I don't like leader units having Intelligent unless they have a lot of XP, and I personally don't like the trope of most Orcs being unintelligent. I would personally suggest against that trait. Fearless and Strong sound good.

**Comment by cooljeanius** [comment]
> Eh.. I don't like leader units having Intelligent unless they have a lot of XP, and I personally don't like the trope of most Orcs being unintelligent. I would personally suggest against that trait. Fearless and Strong sound good.

I don't think that one unit having the "Intelligent" trait implies that other members of that unit's race are unintelligent... now, goblins randomly getting the "Dim" trait might imply that, but that's a separate issue...
