### ISSUE TITLE
Some scenarios may have become TOO easy?

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/Son_Of_The_Black_Eye_Easy_Edition#9]
When trying to graft Yumi's mainline changes for 1.15 onto this branch in 69da735dbf49abab92506217bce3048ccdd41a09, I tried to make sure all my amounts would stay easier than hers. However, in doing so, I may have inadvertently made things TOO easy, to the point where it becomes boring to play. However, to keep the title of "Easy Edition" I really ought to keep all my amounts easier than what's in mainline... maybe it's time to change what the acronym stands for, and make it "Eric's Edition" instead? I'm not too sure about this; leaving open for discussion...

**Comment by cooljeanius** [comment]
Since @nemaara asked me to make a list of the scenarios in question, here's what I've noticed so far:

- [x] Scenario 3, Towards the Mountains of Haag (probably my fault, due to my fix to bug #1 point 1 in fc4e6ae, and all the extra gold-getting opportunities I gave to the player)
- [x] Scenarios with Flar'Tar/Al'Brock (i.e. 12, 13, 14, 17, and 18, which are, respectively, Giving Some Back, The Dwarvish Stand, Back Home, The Human Attack, and Northern Alliance) (this is probably due to them needing to be buffed due to the pending removal of the AI controller, but I am trying to keep the AI controller here as per bug #1 point 3)

**Comment by cooljeanius** [comment]
oh, and also, since I allow level 0 units to be recruited in this version of the campaign, that interacts kinda brokenly with the whole "Great Horde" mechanic, as recruiting level 0 units then actually reduces your total upkeep, which is something that wasn't possible in the original. I may want to fix that as part of this issue, as well...

**Comment by cooljeanius** [comment]
ok I've tested after 6222f5b and can confirm that S03 is better now

**Comment by cooljeanius** [comment]
> oh, and also, since I allow level 0 units to be recruited in this version of the campaign, that interacts kinda brokenly with the whole "Great Horde" mechanic, as recruiting level 0 units then actually reduces your total upkeep, which is something that wasn't possible in the original. I may want to fix that as part of this issue, as well...

This part looks like it's fixed by 53fb508

**Comment by nemaara** [comment]
I'm a bit confused about what you want me to look at ?

**Comment by cooljeanius** [comment]
> I'm a bit confused about what you want me to look at ?

I was just looking for a comparison of my numbers to your numbers, to see if maybe you could toughen some of the ones in mainline, so that I could toughen this in turn while still remaining easier than mainline, but actually on second thought, nvm, I've decided I'm going to go my own direction with this, by compensating in ways that don't depend on what mainline does.

> * [x]  Scenarios with Flar'Tar/Al'Brock (i.e. 12, 13, 14, 17, and 18, which are, respectively, Giving Some Back, The Dwarvish Stand, Back Home, The Human Attack, and Northern Alliance) (this is probably due to them needing to be buffed due to the pending removal of the AI controller, but I am trying to keep the AI controller here)

splitting this up into multiple checkboxes:
* [x] S12, Giving Some Back
* [x] S13, The Dwarven Stand (fixed as of 04b8c4e)
* [x] S14, Back Home (fixed as of f3224db)
* [x] S17, The Human Attack
* [x] S18, Northern Alliance

**Comment by cooljeanius** [comment]
S13 is already checked off, but 4196ab7 also goes towards it

**Comment by cooljeanius** [comment]
> S13 is already checked off, but [4196ab7](https://github.com/cooljeanius/Son_Of_The_Black_Eye_Easy_Edition/commit/4196ab7e0480f6d6be2d4862a49096125cfd54b2) also goes towards it

this is probably too small on its own to merit a new release on the 1.14 server, so I'm going to postpone releasing it and addressing the rest of the scenarios until a post-1.16 release

**Comment by cooljeanius** [comment]
actually nvm I'm un-postponing this; 749ddc8 lets me check the S12 checkbox

**Comment by cooljeanius** [comment]
OK I think this is as good as it's going to get for now; more rebalancing can always be done, but that can be tracked in separate issues.
